export const TEMPLATE_DUMMEY = {
  dummy1: {
    name: "入力のみ",
    style: { icon: "Run", color: "#3B82F6" },
    config: { result_format: "{distance}{duration}\n{location}{memo}" },
    fields: [
      {
        id: "f_memo",
        name: "memo",
        label: "メモ",
        type: "text",
        width: "big",
        placeholder: "自由入力",
        prefix: "",
        suffix: "",
        hide_if_empty: true,
      },
    ],
  },

  dummy2: {
    name: "ランニング記録テンプレート",
    style: { icon: "Run", color: "#3B82F6" },
    config: { result_format: "{distance}{duration}\n{location}{memo}" },
    fields: [
      {
        id: "f_dist",
        name: "distance",
        label: "距離",
        type: "number",
        width: "small",
        placeholder: "0.0",
        prefix: "",
        suffix: "Km",
        hide_if_empty: true,
      },
      {
        id: "f_dur",
        name: "duration",
        label: "時間",
        type: "number",
        width: "small",
        placeholder: "分",
        prefix: "[",
        suffix: "分]",
        hide_if_empty: true,
      },
      {
        id: "f_loc",
        name: "location",
        label: "場所",
        type: "string",
        width: "normal",
        placeholder: "コース名",
        prefix: "[",
        suffix: "]",
        hide_if_empty: true,
      },
      {
        id: "f_memo",
        name: "memo",
        label: "メモ",
        type: "text",
        width: "big",
        placeholder: "体調など",
        prefix: "memo:",
        suffix: "",
        hide_if_empty: true,
      },
    ],
  },
  dummy3: {
    name: "登山テンプレート",
    style: { icon: "Mountain", color: "#16A34A" },
    config: { result_format: "{mountain}{area}{time}" },
    fields: [
      {
        name: "mountain",
        label: "山名",
        type: "string",
        placeholder: "山名",
        prefix: "",
        suffix: "",
        hide_if_empty: true,
      },
      {
        name: "area",
        label: "詳細",
        type: "string",
        placeholder: "ルートなど",
        prefix: "(",
        suffix: ")",
        hide_if_empty: true,
      },
      {
        name: "time",
        label: "所要分",
        type: "number",
        placeholder: "分",
        prefix: "[",
        suffix: "分]",
        hide_if_empty: true,
      },
    ],
  },
};
